repositories {
    flatDir {dirs 'lib'}
}
dependencies {
    testImplementation 'junit:junit:4.13.1'
    implementation 'org.yaml:snakeyaml:1.33'
    implementation 'com.google.code.gson:gson:2.8.9'
    implementation 'net.fabiozumbi12:redprotect:1.9.6'
    implementation 'com.plotsquared:PlotSquared-Bukkit:3.830'
    implementation 'org.primesoft:BlocksHub:2.0'
    implementation 'com.github.luben:zstd-jni:1.1.1'
//    compile 'org.javassist:javassist:3.22.0-CR1'
    implementation 'co.aikar:fastutil-lite:1.0'
    implementation(group: 'com.sk89q.worldedit', name: 'worldedit-core', version:'6.1.4-SNAPSHOT') {
        exclude(module: 'bukkit-classloader-check')
    }
    implementation fileTree(dir: 'libs', include: '*.jar')
}

processResources {
    from('src/main/resources') {
        include 'fawe.properties'
        expand(
                version: "${project.parent.version}",
                name: project.parent.name,
        )
    }
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
}
